---
# tasks file for roles/launch_app
- name: Run App
  community.docker.docker_container:
    name: backendapistudent
    image: nathanglmt/backendapi:1.1
    networks:
      - name: "my_network"
    env:
      POSTGRES_USR: "{{ POSTGRES_USR }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_URL: "{{ POSTGRES_URL }}"
