version: "3.7"

services:
  backend:
    image: nathanglmt/backendapi:1.1
    environment:
      - POSTGRES_USR=usr
      - POSTGRES_DB=db
      - POSTGRES_URL=myfirstpostgres:5432
      - POSTGRES_PASSWORD=pwd
    networks:
      - app-network
    depends_on:
      - database
    container_name: backendapistudent

  database:
    image: nathanglmt/postgres-database:1.0
    environment:
      - POSTGRES_USR=usr
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=pwd
    ports: 
      - "8888:5432"
    networks:
      - app-network
    volumes:
      - dataDir:/var/lib/postgresql/data
    container_name: myfirstpostgres

  httpd:
    image: nathanglmt/httpd:1.0
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - backend
    container_name: mypreciouswebsite

  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8090:8080

networks:
  app-network:

volumes:
  dataDir: