name: CI devops 2024

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build and test with Maven
        run: mvn clean install --file docker/backend/simple-api-student-main/

# define job to build and publish docker image
build-and-push-docker-image:
 needs: test-backend
 # run only when code is compiling and tests are passing
 runs-on: ubuntu-22.04

 # steps to perform in job
 steps:
   - name: Checkout code
     uses: actions/checkout@v2.5.0

   - name: Build image and push backend
     uses: docker/build-push-action@v3
     with:
       # relative path to the place where source code with Dockerfile is located
       context: ./docker/backend/simple-api-student-main/
       # Note: tags has to be all lower-case
       tags:  ${{secrets.DOCKER_USR}}/tp-devops-simple-api:latest

