name: CI devops 2024

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build and test with Maven
        run: mvn clean install --file docker/backend/simple-api-student-main/

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./docker/backend/simple-api-student-main/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backendapi:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./docker/database/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/postgres-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./docker/httpd/website/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/httpd:latest
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./docker/backend/simple-api-student-main/
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/backendapi:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./docker/database/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/postgres-database:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./docker/httpd/website/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/httpd:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
        



