name: Push Docker Image

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed

jobs:
  push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./docker/backend/simple-api-student-main/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backendapi:latest
          push: ${{ github.ref == 'refs/heads/main' }}
